version: '3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    links:
      - db
      - redis
      
  redis:
    image: "redis:alpine"

  db:
    image: "mongo:latest"
    hostname: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=reverse-proxy
    volumes:
      - ../mongodb-docker:/data/db
    ports:
      - 27017:27017
