version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    
  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
      - SERVER_NAME=54.207.249.54
    restart: always
    network_mode: host     
  redis:
    image: "redis:alpine"
    restart: always

  db:
    image: "mongo:latest"
    hostname: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=reverse-proxy
    volumes:
      - ../mongodb-docker:/data/db
    ports:
      - 27017:27017
    restart: always
