version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    links:
      - db
      - redis
  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
      - SERVER_NAME = 0.0.0.0
    restart: always
     
  redis:
    image: "redis:alpine"
    restart: always

  db:
    image: "mongo:latest"
    hostname: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=reverse-proxy
    volumes:
      - ../mongodb-docker:/data/db
    ports:
      - 27017:27017
    restart: always
